issuer: https://token.actions.githubusercontent.com
subject: repo:octo-sts/action:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: octo-sts/action/.github/workflows/use-action.yaml@refs/heads/main

permissions:
  contents: read
  issues: write
