name: Use Action

on:
  workflow_dispatch:
  pull_request_target:
    branches: ['main']
  push:
    branches: ['main']

permissions:
  id-token: write # Needed to federate with octo-sts

jobs:
  use-action:
    name: Use Action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: octo-sts
        uses: ./
        with:
          scope: ${{github.repository}}
          identity: use-action

      - env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: gh issue create --title "Use Action" --body "This issue was created using an Octo STS token" -R ${{github.repository}}
