name: Use Action

on:
  pull_request_target:
    branches: ['main']
  workflow_dispatch:
  push:
    branches: ['main']

permissions:
  id-token: write # Needed to federate with octo-sts

jobs:
  use-action:
    name: Use Action
    runs-on: ubuntu-latest

    steps:
      - id: octo-sts
        uses: octo-sts/action@main
        with:
          scope: octo-sts/action
          identity: use-action

      - uses: actions/checkout@v4
      - env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: gh repo list | grep octo-sts
