name: Use Action

on:
  pull_request_target:
    branches: ['main']

permissions:
  id-token: write # Needed to federate with octo-sts

jobs:
  use-action:
    name: Use Action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: octo-sts
        uses: ./
        with:
          scope: octo-sts/action
          identity: use-action

      - env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: gh repo list | grep octo-sts
